#!/bin/sh
### BEGIN INIT INFO
# Provides:          bootlogo
# Required-Start:    
# Required-Stop:     
# Should-Start:      
# Should-Stop:       
# Default-Start:     S
# Default-Stop:      0 1 6
# Short-Description: boot splash screen display
# Description:       boot splash screen display using the fbi framebuffer image viewer. 
### END INIT INFO


#An internet enabled TV photo frame for the Raspberry Pi
#Copyright (C) 2013 Colin Sauze
      
#This program is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 3 of the License, or
#(at your option) any later version.
                  
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
 
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software Foundation,
#Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
                                       



PATH=/bin:/usr/bin:/sbin:/usr/sbin
DESC="bootlogo"
NAME=bootlogo
PIDFILE=/var/run/bootlogo.pid
PROGRAM="/usr/bin/fbi"
ARGS="--noverbose -vt 1 /home/pi/piframe/loading.png"
SCRIPTNAME=/etc/init.d/"$NAME"

. /lib/lsb/init-functions


case "$1" in
start)	log_daemon_msg "Starting splash screen" "bootlogo"
	#$PROGRAM
        start_daemon -p $PIDFILE $PROGRAM $ARGS
        log_end_msg $?
    ;;
stop)	log_daemon_msg "Stopping splash screen" "bootlogo"
        killproc -p $PIDFILE $DAEMON
        RETVAL=$?
        [ $RETVAL -eq 0 ] && [ -e "$PIDFILE" ] && rm -f $PIDFILE
        log_end_msg $RETVAL
        ;;
restart) log_daemon_msg "Restarting splash screen" "bootlogo" 
        $0 stop
        $0 start
        ;;
reload|force-reload) log_daemon_msg "Restarting splash screen" "bootlogo"
    # cron reloads automatically
        log_end_msg 0
        ;;
status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;
*)	log_action_msg "Usage: /etc/init.d/bootlogo {start|stop|status|restart|reload|force-reload}"
        exit 2
        ;;
esac
exit 0

