#!/bin/sh
### BEGIN INIT INFO
# Provides:          piframe
# Required-Start:    networking
# Required-Stop:     
# Should-Start:      
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: boot splash screen display
# Description:       boot splash screen display using the fbi framebuffer image viewer. 
### END INIT INFO


PATH=/bin:/usr/bin:/sbin:/usr/sbin
DESC="piframe"
NAME=piframe
PIDFILE=/var/run/piframe.pid
PROGRAM="/home/pi/piframe/pi/piframe.sh"
ARGS=""
SCRIPTNAME=/etc/init.d/"$NAME"

. /lib/lsb/init-functions


case "$1" in
start)	log_daemon_msg "Starting piframe" "piframe"
        start_daemon -p $PIDFILE $PROGRAM $ARGS
        log_end_msg $?
    ;;
stop)	log_daemon_msg "Stopping piframe" "piframe"
	killall download_photos.sh
	killall fbi
        killproc -p $PIDFILE $DAEMON
        RETVAL=$?
        [ $RETVAL -eq 0 ] && [ -e "$PIDFILE" ] && rm -f $PIDFILE
        log_end_msg $RETVAL
        ;;
restart) log_daemon_msg "Restarting piframe" "pifrarme" 
        $0 stop
        $0 start
        ;;
reload|force-reload) log_daemon_msg "Restarting piframe" "piframe"
    # cron reloads automatically
        log_end_msg 0
        ;;
status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;
*)	log_action_msg "Usage: /etc/init.d/piframe {start|stop|status|restart|reload|force-reload}"
        exit 2
        ;;
esac
exit 0

